import type { CopyKey } from './keys'

export const zhCN: Record<CopyKey, string> = {
  COPY_TITLE_ENTRY: '安全运行 OpenClaw',
  COPY_TITLE_PREINSTALL: '开始前，请先确认这次隔离 Linux 环境与 OpenClaw 安装会做什么',
  COPY_TITLE_PRECHECK: '先检查你的设备是否已经准备好',
  COPY_TITLE_INSTALLING: '正在准备安全运行环境',
  COPY_TITLE_INSTALL_FAIL: '安装没有完成',
  COPY_TITLE_STATUS: '运行环境状态',
  COPY_TITLE_RECOVERY: '恢复运行环境',
  COPY_TITLE_CONNECTION_FAILURE: '无法连接本地安全组件',
  COPY_TITLE_CONFIRM_PERMISSION: '继续此操作？',
  COPY_TITLE_CONFIRM_REBUILD: '重建隔离运行环境？',
  COPY_TITLE_CONFIRM_DELETE: '删除这个运行环境？',
  COPY_DESC_ENTRY:
    '推荐在隔离环境中运行，减少对本机系统的直接影响。',
  COPY_DESC_SCOPE:
    'OpenClaw 默认运行在隔离 Linux 环境中，而不是直接在 Windows 主环境中运行。',
  COPY_DESC_PERMISSION:
    '首次安装时，系统可能请求必要权限以创建隔离运行环境。',
  COPY_DESC_STORAGE:
    '运行环境会占用一定磁盘空间，后续你可以重建或删除该环境。',
  COPY_DESC_INSTALLING:
    '这可能需要几分钟。过程中系统可能会请求一次必要权限，用来准备隔离 Linux 环境和 OpenClaw 运行环境。',
  COPY_DESC_FAIL_SAFE:
    '你的 Windows 主环境没有被直接用于运行 OpenClaw。你可以按下面的方式继续。',
  COPY_DESC_STATUS_SAFE:
    '当前 OpenClaw 运行在隔离环境中；如环境异常，你可以随时重建或删除该环境。',
  COPY_DESC_RECOVERY:
    '如果 OpenClaw 无法正常运行，你可以先尝试重试；如果问题持续，可以重建环境；如果不再需要，也可以彻底删除。',
  COPY_DESC_CONNECTION_FAILURE:
    '当前页面还没有建立到本地安全组件的受信连接，因此不会显示伪造的成功状态。',
  COPY_ERR_UNSUPPORTED_SYSTEM: '你的设备暂时不支持这种隔离运行方式。',
  COPY_ERR_FEATURE_MISSING: '你的设备还没有开启隔离运行所需的系统能力。',
  COPY_ERR_DISK_LOW: '可用空间不足，暂时无法创建运行环境。',
  COPY_ERR_NETWORK: '连接中断，安装没有完成。',
  COPY_ERR_PERMISSION: '没有取得这一步所需的系统权限，因此安装没有完成。',
  COPY_ERR_TIMEOUT: '准备运行环境花费的时间比预期更长，这次没有完成。',
  COPY_ERR_PARTIAL_INSTALL: '环境只完成了一部分，建议进入恢复中心继续处理。',
  COPY_ERR_ENV_CORRUPTED: '当前运行环境状态异常，建议先重建环境。',
  COPY_ERR_UNKNOWN: '这次没有完成，你可以先重试；如果问题持续，进入恢复中心。',
  COPY_BTN_CHOOSE_LOCAL: '选择本机隔离 Linux 环境',
  COPY_BTN_CONTINUE: '继续',
  COPY_BTN_START_INSTALL: '一键安装隔离 Linux 环境与 OpenClaw',
  COPY_BTN_FIX_FIRST: '查看修复方法',
  COPY_BTN_CONTINUE_ANYWAY: '仍要继续',
  COPY_BTN_RETRY_INSTALL: '重试安装',
  COPY_BTN_OPEN_RECOVERY: '进入恢复中心',
  COPY_BTN_START_AGENT: '启动 OpenClaw',
  COPY_BTN_STOP_AGENT: '停止运行',
  COPY_BTN_RESTART_ENV: '重启环境',
  COPY_BTN_RETRY: '立即重试',
  COPY_BTN_REBUILD: '重建环境',
  COPY_BTN_DELETE: '删除环境',
  COPY_BTN_CANCEL: '取消',
  COPY_BTN_RETRY_CONNECTION: '重试连接',
  COPY_BTN_RECONNECT: '重新建立连接',
  COPY_BTN_VIEW_FIX_INSTRUCTIONS: '查看修复方法',
  COPY_BTN_COPY_DIAGNOSTICS: '复制诊断摘要',
  COPY_BTN_REFRESH_SNAPSHOT: '刷新状态',
  COPY_BTN_OPEN_ONBOARDING: '打开 OpenClaw 引导',
  COPY_BTN_CONFIRM_REBUILD: '重建',
  COPY_BTN_CONFIRM_DELETE: '删除环境',
  COPY_CONFIRM_PERMISSION_BODY:
    '为了完成这一步，系统可能请求必要权限，用于创建或修复隔离运行环境。',
  COPY_CONFIRM_REBUILD_BODY:
    '这会删除当前环境并重新创建。该环境中的临时内容可能丢失，但不会把 OpenClaw 直接切到 Windows 主环境里运行。',
  COPY_CONFIRM_REBUILD_CHECK: '我知道重建会清空当前隔离环境中的内容。',
  COPY_CONFIRM_PERMISSION_IMPACT: '这一步会请求系统授权，以继续当前安装或恢复动作。',
  COPY_CONFIRM_PERMISSION_SAFE: '不会把 OpenClaw 切换到 Windows 主环境直接运行。',
  COPY_CONFIRM_REBUILD_IMPACT: '会删除当前隔离环境并重新创建，当前环境内的临时内容可能丢失。',
  COPY_CONFIRM_REBUILD_SAFE: '不会改成在 Windows 主环境直接运行 OpenClaw，也不会自动删除你的整机内容。',
  COPY_CONFIRM_DELETE_BODY:
    '删除后，这个隔离运行环境及其中内容将被移除。你之后仍可重新安装。',
  COPY_CONFIRM_DELETE_SCOPE: '这不会自动删除你的整个 Windows 系统内容。',
  COPY_CONFIRM_DELETE_IMPACT: '会移除当前隔离运行环境及其中内容，之后若要继续需要重新安装。',
  COPY_CONFIRM_DELETE_SAFE: '不会自动删除你的整个 Windows 系统内容，也不会影响未纳入隔离环境的内容。',
  COPY_LABEL_RECOMMENDED: '推荐',
  COPY_LABEL_RUNTIME_LOCATION: '运行位置',
  COPY_LABEL_DIRECT_IMPACT: '对主系统影响',
  COPY_LABEL_WILL_AFFECT: '会影响什么',
  COPY_LABEL_WILL_NOT_AFFECT: '不会影响什么',
  COPY_LABEL_LAST_OPERATION: '最近操作',
  COPY_LABEL_STATE: '当前状态',
  COPY_LABEL_STATUS_SUMMARY: '状态摘要',
  COPY_LABEL_MAINTENANCE: '维护操作',
  COPY_LABEL_RECOVERY_ACTIONS: '恢复动作',
  COPY_LABEL_CHECK_RESULTS: '预检结果',
  COPY_LABEL_INSTALL_PATH: '安装路径说明',
  COPY_LABEL_RECOVERY_PATH: '恢复路径说明',
  COPY_LABEL_CHECKING: '检查中',
  COPY_LABEL_WARN_CONTINUE: '存在需要留意的项，但你仍可继续。',
  COPY_LABEL_BLOCKED: '存在阻塞项，完成处理前不能开始安装。',
  COPY_LABEL_DEVTOOLS: '调试入口',
  COPY_LABEL_FIXED_ACTIONS: '页面固定动作',
  COPY_LABEL_STEP_CURRENT: '当前步骤',
  COPY_LABEL_FAILURE_INFO: '失败信息',
  COPY_LABEL_DIAGNOSTICS: '诊断摘要',
  COPY_LABEL_RECOMMENDED_NEXT: '推荐下一步',
  COPY_LABEL_OPENCLAW_RUNTIME: 'OpenClaw 运行时',
  COPY_LABEL_ONBOARDING: '初始配置',
  COPY_HINT_PERMISSION_PROMPT: '系统可能会请求一次必要权限。',
  COPY_HINT_REBUILD_IMPACT: '会清空当前隔离环境中的内容，但不会把 OpenClaw 切到 Windows 主环境运行。',
  COPY_HINT_DELETE_IMPACT: '会删除隔离环境及其中内容，之后需要重新安装才能继续本机运行。',
  COPY_HINT_SAFE_SCOPE: '始终保持本机隔离运行，减少对 Windows 主环境的直接影响。',
  COPY_HINT_ACTION_REQUIRED: '需要进一步处理',
  COPY_PROMISE_ISOLATED: '默认运行在隔离环境中',
  COPY_PROMISE_RECOVERABLE: '出问题后可重试、重建环境或删除环境',
  COPY_PROMISE_SYSTEM_TOOL: '更像系统工具，而不是一次性安装页',
  COPY_ENTRY_LOCAL_TITLE: '本机隔离 Linux 环境',
  COPY_ENTRY_LOCAL_ITEM_1: '与主系统分开运行，减少直接影响。',
  COPY_ENTRY_LOCAL_ITEM_2: '后续可以重建环境或删除环境。',
  COPY_ENTRY_LOCAL_ITEM_3: '首次安装需要准备运行环境并占用一定磁盘空间。',
  COPY_PREINSTALL_PERMISSION_TITLE: '什么时候会请求权限',
  COPY_PREINSTALL_RECOVERY_TITLE: '之后能不能重建或删除',
  COPY_PREINSTALL_CHECK_SCOPE: '我已了解这会在本机创建隔离运行环境。',
  COPY_PREINSTALL_CHECK_RECOVERY: '我知道后续可以重建环境或删除环境。',
  COPY_PRECHECK_WARN_DESC: '警告项不会阻止安装，但需要你显式确认仍要继续。',
  COPY_PRECHECK_BLOCK_DESC: '阻塞项存在时，主按钮固定为查看修复方法。',
  COPY_PRECHECK_FIX_TITLE: '修复方法',
  COPY_PRECHECK_FIX_ITEM_1: '先处理阻塞项，再重新检查。',
  COPY_PRECHECK_FIX_ITEM_2: '若仅有警告项，可在理解风险后继续。',
  COPY_PRECHECK_FIX_ITEM_3: '若问题持续，请导出诊断包并联系支持。',
  COPY_INSTALLING_PROGRESS_TITLE: '正在准备隔离 Linux 环境与 OpenClaw 运行环境',
  COPY_INSTALL_FAILED_RETRY_TITLE: '优先重试',
  COPY_INSTALL_FAILED_RETRY_DESC: '适用于网络波动、初始化超时或权限未完成的临时失败。',
  COPY_INSTALL_FAILED_REBUILD_TITLE: '再决定是否重建',
  COPY_INSTALL_FAILED_REBUILD_DESC: '若环境状态已经不一致，再进入恢复中心处理。',
  COPY_INSTALL_FAILED_NEXT_TITLE: '下一步建议',
  COPY_INSTALL_FAILED_NEXT_ITEM_1: '临时失败时先重试，不删除现有环境。',
  COPY_INSTALL_FAILED_NEXT_ITEM_2: '若环境只完成了一部分，优先进入恢复中心。',
  COPY_INSTALL_FAILED_NEXT_ITEM_3: '如反复失败，请导出诊断包并进入恢复中心继续处理。',
  COPY_STATUS_PRIMARY_ACTIONS: '主操作',
  COPY_STATUS_MAINTENANCE_TITLE: '维护操作',
  COPY_STATUS_NO_LAST_ACTION: '尚未执行动作',
  COPY_RECOVERY_SCOPE_NOTE: '所有恢复动作都围绕隔离环境本身，不把 OpenClaw 切到 Windows 主环境运行。',
  COPY_NOTICE_BRIDGE_FALLBACK:
    '当前无法连接本地安全组件，请先恢复本地 bridge 连接后再继续。',
  COPY_NOTICE_DIAGNOSTICS_COPIED: '诊断摘要已复制。',
  COPY_NOTICE_ONBOARDING_COPIED: 'OpenClaw 引导地址已复制。',
  COPY_DEBUG_SCENARIO_TITLE: '场景模板',
  COPY_STEP_CHECK: '检查系统能力',
  COPY_STEP_CREATE: '创建隔离环境',
  COPY_STEP_CONFIGURE: '配置 OpenClaw 运行环境',
  COPY_STEP_VERIFY: '完成验证',
  COPY_CHECK_SYSTEM_VERSION_TITLE: '系统版本',
  COPY_CHECK_SYSTEM_VERSION_DESC: '确认你的设备支持本机隔离运行所需的基础条件。',
  COPY_CHECK_ISOLATION_CAPABILITY_TITLE: '隔离环境能力',
  COPY_CHECK_ISOLATION_CAPABILITY_DESC: '确认本机隔离运行所需能力已经准备好。',
  COPY_CHECK_VIRTUALIZATION_TITLE: '虚拟化能力',
  COPY_CHECK_VIRTUALIZATION_DESC: '确认设备具备创建隔离环境所需的虚拟化基础。',
  COPY_CHECK_DISK_SPACE_TITLE: '磁盘空间',
  COPY_CHECK_DISK_SPACE_DESC: '确认有足够空间创建和运行隔离环境。',
  COPY_CHECK_NETWORK_TITLE: '网络状态',
  COPY_CHECK_NETWORK_DESC: '确认安装资源可被正常访问。',
  COPY_CHECK_PERMISSION_READY_TITLE: '权限条件',
  COPY_CHECK_PERMISSION_READY_DESC: '安装过程中可能需要一次必要权限确认。',
  COPY_STATUS_NOT_INSTALLED: '未安装',
  COPY_STATUS_PRECHECK_REQUIRED: '待预检',
  COPY_STATUS_READY_TO_INSTALL: '可开始安装',
  COPY_STATUS_INSTALLING: '安装中',
  COPY_STATUS_INSTALL_FAILED: '安装失败',
  COPY_STATUS_READY: '环境可用',
  COPY_STATUS_STARTING: '正在启动',
  COPY_STATUS_RUNNING: '运行中',
  COPY_STATUS_STOPPED: '已停止',
  COPY_STATUS_DEGRADED: '需要恢复',
  COPY_STATUS_REBUILDING: '重建中',
  COPY_STATUS_DELETING: '删除中',
  COPY_RECOVERY_RETRY_TITLE: '重试',
  COPY_RECOVERY_RETRY_DESC: '适用于临时失败；不删除现有环境；保留当前配置与内容。',
  COPY_RECOVERY_REBUILD_TITLE: '重建环境',
  COPY_RECOVERY_REBUILD_DESC:
    '适用于环境状态异常或反复启动失败；会删除当前隔离环境并重新创建。',
  COPY_RECOVERY_DELETE_TITLE: '删除环境',
  COPY_RECOVERY_DELETE_DESC:
    '适用于不再使用或想完全清理后再开始；删除后需要重新安装才能继续本机运行。',
  COPY_DEBUG_SCENARIO_FIRST_INSTALL: '首次安装默认',
  COPY_DEBUG_SCENARIO_PRECHECK_BLOCKED: '预检阻塞',
  COPY_DEBUG_SCENARIO_PRECHECK_WARN: '预检警告可继续',
  COPY_DEBUG_SCENARIO_INSTALL_NETWORK_FAILED: '安装下载失败',
  COPY_DEBUG_SCENARIO_PARTIAL_INSTALL: '部分安装失败',
  COPY_DEBUG_SCENARIO_DEGRADED: '启动连续失败后降级',
  COPY_DEBUG_SCENARIO_REBUILDING: '重建中',
  COPY_DEBUG_SCENARIO_DELETING: '删除中',
  COPY_DEBUG_SCENARIO_DELETE_SUCCESS: '删除成功返回启动页',
  COPY_DEBUG_SCENARIO_PERMISSION_PREVIEW: '权限确认预演',
  COPY_DEBUG_APPLY_SCENARIO: '应用场景',
}
